dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: nodey216
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: nodey220
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: nodey221
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: nodey222
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
